[phases.setup]
nixPkgs = ["rustc", "cargo", "openssl", "pkg-config"]

[phases.install]
cmds = []

[phases.build]
cmds = ["cd backend-rust && cargo build --release"]

[start]
cmd = "./backend-rust/target/release/server"
